apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: gitallsecrets-cron
  namespace: kubebot-server
  labels:
    app: cronjob-worker
    component: cronjob
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: checkfile-container
            image: us.gcr.io/kubebot-163519/utils/utils_checkfile:0.1.0
            imagePullPolicy: IfNotPresent
            env:
            - name: gitpersonaltoken
              value: ""
            - name: githubowner
              value: "kubebot-user"
            - name: githubacturl
              value: "https://github.com/kubebot-user"
            - name: slackwebhookurl
              value: ""
            args:
            - /tmp/results/gitallsecrets_secretorg123
            volumeMounts:
            - name: results
              mountPath: /tmp/results
            - name: secretstore
              mountPath: /secretstore
          restartPolicy: OnFailure
          volumes:
          - name: results
            emptyDir: {}
          - name: secretstore
            secret:
              secretName: googlesecret
          initContainers:
          - name: gitallsecrets-init-container
            image: us.gcr.io/kubebot-163519/tools/tools_gitallsecrets:0.1.0
            imagePullPolicy: IfNotPresent
            args:
            - -toolName
            - repo-supervisor
            - -org
            - secretorg123
            - -output
            - /tmp/results/gitallsecrets_secretorg123
            - -token
            -
            volumeMounts:
            - name: results
              mountPath: /tmp/results
          restartPolicy: OnFailure